config/routes.rb
Refinery::Application.routes.draw do  
  scope(:path => 'download', :module => 'download') do
    root :to => 'files#index' , :as => 'download_root'
  end
  
  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    scope(:path => 'download', :as => 'download', :module => 'download') do
      root :to => 'files#index'
      resources :files 
      resources :categories
    end
    
  end
end

app/models/download.rb
class Download < ActiveRecord::Base

  acts_as_indexed :fields => [:title]

  validates :title, :presence => true, :uniqueness => true
  
  belongs_to :file, :class_name => 'Resource'
  
  ICONS = [ 'pdf', 'doc' ]      
   
end

app/models/download_category.rb
class DownloadCategory < ActiveRecord::Base 
  acts_as_indexed :fields => [:title]

  validates :title, :presence => true, :uniqueness => true
  
  has_many :download_files
end

app/models/download_file.rb
class DownloadFile < ActiveRecord::Base

  acts_as_indexed :fields => [:title]

  validates :title, :presence => true, :uniqueness => true
  
  belongs_to :file, :class_name => 'Resource'
  belongs_to :download_category  
   
end

app/controllers/admin/download/categories_controller.rb
class Admin::Download::CategoriesController < Admin::BaseController
  
  crudify :download_category


end

app/controllers/admin/download/files_controller.rb
class Admin::Download::FilesController < Admin::BaseController
  
  crudify :download_file

end

app/controllers/download/files_controller.rb
class Download::FilesController < ApplicationController
  helper :downloads
  before_filter :find_all_categories
  before_filter :find_page
  before_filter :authorize_as_private_user
  
  def index
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @download in the line below:
    present(@page)
  end

protected

  def find_all_categories
    @categories = DownloadCategory.find(:all, :order => "position ASC")
  end

  def find_page
    @page = Page.find_by_link_url("/download")
  end
  
  def authorize_as_private_user 
    if current_user 
     redirect_to root_url unless current_user.has_role?(:downloads) || current_user.has_role?(:superuser)
    elsif !current_user
     redirect_to new_user_session_path
    end
  end

end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController

  before_filter :find_all_downloads
  before_filter :find_page
  before_filter :authorize_as_private_user
  
  def index
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @download in the line below:
    present(@page)
  end

protected

  def find_all_downloads
    @downloads = Download.find(:all, :order => "position ASC")
  end

  def find_page
    @page = Page.find_by_link_url("/downloads")
  end
  
  def authorize_as_private_user 
    if current_user 
     redirect_to root_url unless current_user.has_role?(:downloads)
    elsif !current_user
     redirect_to new_user_session_path
    end
  end

end

app/helpers/downloads_helper.rb
module DownloadsHelper
  def fileicon(download)
    if download.file.file_ext.present?
      refinery_icon_tag("#{download.file.file_ext}.png")
    else
      refinery_icon_tag('page_white_put.png')
    end     
  end
  
  def filelink(download)
    "onclick=\"window.location.href='#{download.file.url}';\" ".html_safe unless download.file.blank?
  end
end

app/views/admin/download/_submenu.html.erb
<nav id='actions' class='multilist'>
  <ul class='search_list'>
    <li class='not_a_link'>
      <%= render :partial => "/shared/admin/search",
                 :locals => {
                   :url => admin_download_files_url
                 } %>
    </li>
  </ul>

  <ul class='collapsible_menu'>
    <li class='not_a_link'>
      <%= link_to t('.files.title'), '#',
                   :class => 'page_copy_icon' %>
    </li>
    <li>
      <%= link_to t('.files.manage'), admin_download_files_path,
                   :class => 'page_icon' %>
    </li>
    <li>
       <%= link_to t('.files.new'), new_admin_download_file_url,
                   :class => 'page_add_icon' %>
    </li>
  </ul>

  <ul class='collapsible_menu'>
    <li class='not_a_link'>
      <%= link_to t('.categories.title'), '#',
                  :class => 'folder_icon' %>
    </li>
    <li>
      <%= link_to t('.categories.manage'), admin_download_categories_url,
                  :class => 'folder_edit_icon' %>
    </li>
    <li>
      <%= link_to t('.categories.new'), new_admin_download_category_url(:dialog => true, :height => 325),
                  :class => 'folder_add_icon' %>
    </li>
  </ul>

</nav>

app/views/admin/download/categories/_category.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(category) -%>">
  <span class='title'>
    <%= category.title %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_edit.png"),
                edit_admin_download_category_path(category, :dialog => true, :height => 325),
                :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_download_category_path(category),
                :class => "cancel confirm-delete",
                :title => t('.delete'),
                :method => :delete,
                :confirm => t('shared.admin.delete.message', :title => category.title) %>
  </span>
</li>

app/views/admin/download/categories/_form.html.erb
<%= form_for [:admin, @download_category] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages",
             :locals => {
               :object => f.object,
               :include_object_name => true
             } %>

  <div class='field'>
    <%= f.label :title -%>
    <%= f.text_field :title, :class => 'larger widest' -%>
  </div>

  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('admin.download.categories.category.delete')
              } %>
<% end %>          

app/views/admin/download/categories/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'category', :collection => @download_categories %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
           :locals => {
             :continue_reordering => (defined?(continue_reordering) ? continue_reordering : true)
           } %>

app/views/admin/download/categories/edit.html.erb
<%= render :partial => 'form' %>

app/views/admin/download/categories/index.html.erb
<%= render :partial => '/admin/download/submenu' %>
<div id='records'>
  <% if searching? %>
    <h2><%= t('shared.admin.search.results_for', :query => params[:search]) %></h2>
    <% if @download_categories.any? %>
      <%= render :partial => "download_categories",
                 :collection => @download_categories %>
    <% else %>
      <p><%= t('admin.search_no_results') %></p>
    <% end %>
  <% else %>
    <% if @download_categories.any? %>
      <%= will_paginate @download_categories %>

      <%= render :partial => "sortable_list" %>

      <%= will_paginate @download_categories %>
    <% else %>
      <p>
        <strong>
          <%= t('.no_items_yet', :create => t('admin.blog.submenu.categories.new')) %>
        </strong>
      </p>
    <% end %>
  <% end %>
</div>

app/views/admin/download/categories/new.html.erb
<%= render :partial => 'form' %>

app/views/admin/download/files/_file.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(file) -%>">
  <span class='title'>
    <%= file.download_category.title %> - <strong><%= file.title %></strong>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_download_file_path(file),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_download_file_path(file),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => file.title),
        :method => :delete %>
  </span>
</li>

app/views/admin/download/files/_form.html.erb
<%= form_for [:admin, @download_file] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => f.object,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :title -%>
    <%= f.text_field :title, :class => 'larger widest' -%>
  </div>
  
  <div class='field'>
    <%= f.label :file -%>
    <%= render :partial => "/shared/admin/resource_picker", :locals => {
          :f => f,
          :field => :file_id,
          :resource => @download_file.file,
        } %>
  </div>
  
  <div class="field">
    <%= f.label :download_category_id, t('.categorytitle') %>
    <%= f.collection_select :download_category_id, DownloadCategory.all, :id, :title %>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.downloads.download'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @download_file.title)
              } %>
<% end -%>

app/views/admin/download/files/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'file', :collection => @download_files %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/download/files/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/download/files/index.html.erb
<%= render :partial => '/admin/download/submenu' %>    
<div id='records'>
  <% if searching? %>
    <h2><%= t('shared.admin.search.results_for', :query => params[:search]) %></h2>
    <% if @download_files.any? %>
    <ul>
      <%= render :partial => "file",
                 :collection => @download_files %>
    </ul>
    <% else %>
      <p><%= t('shared.admin.search.no_results') %></p>
    <% end %>
  <% else %>
    <% if @download_files.any?  %>
      <%= will_paginate @download_files %>

      <%= render :partial => "sortable_list" %>

      <%= will_paginate @download_files %>
    <% else %>
      <p>
        <strong>
          <%= t('.no_items_yet', :create => t('admin.blog.submenu.posts.new')) %>
        </strong>
      </p>
    <% end %>
  <% end %>
</div>

app/views/admin/download/files/new.html.erb
<%= render :partial => "form" %>

app/views/admin/downloads/_form.html.erb
<%= form_for [:admin, @download] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @download,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :title -%>
    <%= f.text_field :title, :class => 'larger widest' -%>
  </div>
  
  <div class='field'>
    <%= f.label :file -%>
    <%= render :partial => "/shared/admin/resource_picker", :locals => {
          :f => f,
          :field => :file_id,
          :resource => @download.file,
        } %>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.downloads.download'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @download.title)
              } %>
<% end -%>

app/views/admin/downloads/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'download', :collection => @downloads %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/download/files/index.html.erb
<% content_for :body_content_left do %>        

  <% if current_user && !current_user.has_role?(:refinery) %>
  <p class="userbuttons">
    <%= link_to 'Log out', destroy_user_session_path, :class => "link-button-more" %>
  </p>
  <% end %>  
  
  <%= raw @page[:body] %>
  
  <% @categories.each do |category| %>
    <% if category.download_files.any? %>
    <table class="download full">
      <caption><%= category.title %></caption>
      <!-- <tr>
        <th><%= t('.filename') %></th>
        <th><%= t('.filesize') %></th>
        <th><%= t('.filetype') %></th> 
      </tr>    -->
      <% category.download_files.each do |file| %>  
      <tr <%= filelink(file) %>>
        <td><%= file.title %></td>
        <td class="size"><%= number_to_human_size(file.file.file_size) unless file.file.blank? %> </td>
        <td class="icon"><%= link_to fileicon(file), file.file.url, :target => '_blank' unless file.file.blank? %></td>
      </tr>
      <% end %>
    </table>
    <% end %>
  <% end %>
<% end %>

<%= render :partial => "/shared/content_page" %>